---
prometheus_nodeport: 30090
grafana_nodeport: 30300
alertmanager_nodeport: 30093
grafana_admin_password: "admin"
slack_webhook_url: ""
slack_channel: ""
cpu_alert_threshold: 20
memory_alert_threshold: 85
disk_alert_threshold: 80
